using System.Security.Cryptography;
using System.Text;

namespace Fortress.Mobile.Core.Services
{
    /// <summary>
    /// Provides a per-vault ephemeral HMAC-SHA256 key used exclusively during a
    /// single import session to group reused passwords without storing or logging
    /// plaintext password hashes.
    ///
    /// Security properties
    /// ───────────────────
    /// – The key is 32 bytes generated by <see cref="RandomNumberGenerator"/> each
    ///   time a new import session begins.
    /// – The key is NEVER persisted to preferences, the database, or any log.
    /// – Using HMAC-SHA256 instead of plain SHA-256 prevents an attacker who obtains
    ///   the import-time memory snapshot from precomputing a rainbow table of common
    ///   passwords – they would also need the ephemeral key.
    /// – The same key instance is reused across all candidates in one preview/commit
    ///   cycle so grouping is consistent, then discarded.
    /// – Zeroed in <see cref="Dispose"/>.
    /// </summary>
    public sealed class ImportHmacProvider : IDisposable
    {
        private byte[] _key;
        private bool _disposed;

        public ImportHmacProvider()
    {
            _key = RandomNumberGenerator.GetBytes(32);
        }

        /// <summary>
        /// Computes HMAC-SHA256(<paramref name="password"/>, <see cref="_key"/>)
  /// and returns the result as a lowercase hex string.
        /// </summary>
        public string ComputeTag(string password)
     {
    ObjectDisposedException.ThrowIf(_disposed, this);

            if (string.IsNullOrEmpty(password))
       return string.Empty;

            var inputBytes = Encoding.UTF8.GetBytes(password);
            var tag = HMACSHA256.HashData(_key, inputBytes);

            // Zero the input bytes – the password is still in the managed heap at
            // the call-site, but we do not hold a reference to it here.
            CryptographicOperations.ZeroMemory(inputBytes);
         return Convert.ToHexString(tag).ToLowerInvariant();
     }

     public void Dispose()
   {
            if (_disposed) return;
     CryptographicOperations.ZeroMemory(_key);
            _key = Array.Empty<byte>();
            _disposed = true;
        }
    }
}
