using LiteDB;

namespace Fortress.Mobile.Core.Models
{
    /// <summary>
    /// Stores a FIDO2/WebAuthn passkey credential.
    ///
  /// On creation the relying-party generates a keypair:
    ///   - The PUBLIC  key is sent to the server (rpId + userHandle + credentialId).
    ///   - The PRIVATE key is stored here, encrypted with the vault master key.
    ///
    /// On assertion (login) the private key is decrypted and used to sign the
  /// FIDO2 challenge returned by the server.
    ///
    /// Algorithm support: ES256 (ECDSA P-256) – the universal default.
    /// </summary>
    public sealed class PasskeyItem
    {
        // ── Identity ──────────────────────────────────────────────────────
   [BsonId]
      public Guid Id { get; set; } = Guid.NewGuid();

        /// <summary>Relying-party ID, e.g. "github.com". Used to match during fill.</summary>
        public string RpId { get; set; } = string.Empty;

        /// <summary>Human-readable service name, e.g. "GitHub".</summary>
   public string RpName { get; set; } = string.Empty;

   // ── User ──────────────────────────────────────────────────────────
        /// <summary>userHandle bytes (Base64Url). Opaque to the client.</summary>
        public string UserHandle { get; set; } = string.Empty;

        /// <summary>User display name / email shown in the picker.</summary>
        public string UserName { get; set; } = string.Empty;

        /// <summary>User display name (may differ from UserName).</summary>
    public string UserDisplayName { get; set; } = string.Empty;

     // ── Key material ──────────────────────────────────────────────────
        /// <summary>
     /// Base64Url-encoded credential ID generated by this client.
    /// Sent to the server and included in every assertion.
   /// </summary>
        public string CredentialId { get; set; } = string.Empty;

    /// <summary>
        /// The private key, encrypted with the vault's master key.
        /// Algorithm: ES256 (ECDSA P-256), stored as PKCS#8 DER then encrypted.
  /// Never transmitted outside the device.
     /// </summary>
        public string EncryptedPrivateKey { get; set; } = string.Empty;

        /// <summary>
        /// The public key in COSE format (CBOR), Base64Url-encoded.
        /// Sent to the server during registration; stored here for display/verification.
        /// </summary>
        public string PublicKeyCose { get; set; } = string.Empty;

        // ── Metadata ──────────────────────────────────────────────────────
     /// <summary>COSE algorithm identifier. -7 = ES256.</summary>
        public int Algorithm { get; set; } = -7;

      /// <summary>Number of times this passkey has been used for assertions.</summary>
 public uint SignCount { get; set; }

     public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>Optional favicon URL for display in the picker.</summary>
        public string? IconUri { get; set; }
    }
}
